services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: meeplesshelf
      POSTGRES_PASSWORD: meeplesshelf
      POSTGRES_DB: meeplesshelf
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
